name: Demo Label

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: contains ( github.event.label.name, 'squad')
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    - name: Echo
      run: echo teste 
